services:
  _defaults:
    public: false

  Van\Translation\:
    resource: '../../'

  translator:
    class: Van\Translation\Translator
    public: true
    arguments:
    - '@service_container'

  translator.loader:
    class: Van\Translation\FileLoader
    public: true
    arguments:
    - '@service_container'
